const express = require('express')
const auth = require('./auth')
const user = require('./user')
const profile_server = require("./profile_server")
const comment = require("./comment")
const followers = require("../controllers/follow/getFollowers")
const followings = require("../controllers/follow/getFollowings")
const freeNFTDrops = require("../controllers/NFT/freeNFTDrops")
const token = require("../controllers/NFT/token")
const refreshNftMetadata = require('../controllers/NFT/refreshNftMetadata')
const fetchLikes = require('../controllers/NFT/fetchLikes')
const nftDetail = require('../controllers/NFT/nftDetail')
const search = require("../controllers/search/search")
const profileTabs = require("../controllers/profile/profileTabs")
const trending = require("../controllers/trending/trending")
const profileNFTs = require("../controllers/profile/profileNFTs")
const getTrendingNFTs = require("../controllers/NFT/trendingNFTs")

const { tokenDecode } = require('../controllers/profile/profileGetters')
const rnlot = require('../controllers/notifications/resetNotificationLastOpenedTime')
const router = express.Router()

router.use('/auth', auth)
router.use('/users', user)
router.use("/profile_server", profile_server)
router.use("/comments", comment)
router.get("/people", followers)
router.get("/peoples", followings)
router.get("/feed/nfts", freeNFTDrops)
router.get("/token/:contractAddress/:tokenId/:chainName", token)
router.post("/nftmetadata/:nft_id", refreshNftMetadata)
router.get("/likes/:nftId", fetchLikes)
router.get("/nft_detail/:nftId", nftDetail)

router.post("/v1/check_notifications", tokenDecode, rnlot)
router.get("/v2/search", search)
router.get("/v2/profile-tabs/tabs", profileTabs)
router.get("/v2/profile-tabs/nfts", profileNFTs)
router.get("/v2/follow-suggestions", trending)
router.get("/v2/trending/nfts", getTrendingNFTs)

module.exports = router
